WiFi RSSI Retrieval and update README for Clarity
ms32035/home-assistant-ubibot pull request #5
Opened 2024-08-31 22:03 UTC by ToledoEM

# Pull Request: Update README for Clarity and WiFi RSSI Retrieval

## Description

This update improves the README file by providing clearer instructions on the configuration for HA.

## Changes

* Updated README to reflect accurate information on retrieving WiFi RSSI from the API
* Added example code snippets for clarity

## Impact

With this change, users can now easily access and utilize the WiFi RSSI data provided by the API.

![image](https://github.com/user-attachments/assets/08a23b7b-5aa8-42a6-b4d4-88d6c7e4b4b1)

2024-08-31 23:52 UTC, ms32035 requested changes
Thank you for the contribution, I've added com comments

2024-08-31 23:52 UTC, ms32035 commented on .DS_Store
Please remove this file

2024-08-31 23:52 UTC, ms32035 commented on .gitignore
This should be part of your global `.gitignore` not this repo

2024-08-31 23:52 UTC, ms32035 commented on custom_components/ubibot/const.py
> +    SIGNAL_STRENGTH_DECIBELS_MILLIWATT
Comma missing, please run the pre-commit hooks. You can upgrade them as well

2024-08-31 23:52 UTC, ms32035 commented on custom_components/ubibot/const.py
> +MODELS = {"ubibot-ws1": "WS1"}
EOL/EOF should not be changed. I believe pre-commit should detect that

2024-09-01 08:41 UTC, ToledoEM commented
Perfect, this is not my thing and now I learned what a pre-commit hook is. I see tha value of them.

2024-09-01 13:43 UTC, merged